version: '3.7'

services:
  callback:
    image: blipmaps.nl/callback:latest
    build: .
    restart: always
    volumes:
      - /tmp/OUT:/data
    environment:
      - OFFSET_HOUR=${offset:-0}
      - targetUrl=${targetUrl:-}
      - uploadXblFiles=${uploadXblFiles:-}
    command: [ "foobar" ]
    secrets:
      - host_ssh_key
      - host_ssh_pub_key
      - host_ssh_known_hosts

secrets:
  host_ssh_key:
    file: ~/.ssh/id_ed25519
  host_ssh_pub_key:
    file: ~/.ssh/id_ed25519.pub
  host_ssh_known_hosts:
    file: ~/.ssh/known_hosts

