version: '3.7'

services:
  netherlands0:
    image: blipmaps.nl/combined:latest
    build: .
    volumes:
      - /tmp/OUT:/root/rasp/NETHERLANDS/OUT
      - /tmp/LOG:/root/rasp/NETHERLANDS/LOG
    environment:
      - START_DAY=0
      - OFFSET_HOUR=${offset:-0}
    command: [ "runRasp.sh","NETHERLANDS" ]

  netherlands1:
    image: blipmaps.nl/combined:latest
    build: .
    volumes:
      - /tmp/OUT:/root/rasp/NETHERLANDS/OUT
      - /tmp/LOG:/root/rasp/NETHERLANDS/LOG
    environment:
      - START_DAY=1
      - OFFSET_HOUR=${offset:-0}
    command: [ "runRasp.sh","NETHERLANDS" ]

  netherlands2:
    image: blipmaps.nl/combined:latest
    build: .
    volumes:
      - /tmp/OUT:/root/rasp/NETHERLANDS/OUT
      - /tmp/LOG:/root/rasp/NETHERLANDS/LOG
    environment:
      - START_DAY=2
      - OFFSET_HOUR=${offset:-0}
    command: [ "runRasp.sh","NETHERLANDS" ]

  netherlands3:
    image: blipmaps.nl/combined:latest
    build: .
    volumes:
      - /tmp/OUT:/root/rasp/NETHERLANDS/OUT
      - /tmp/LOG:/root/rasp/NETHERLANDS/LOG
    environment:
      - START_DAY=3
      - OFFSET_HOUR=${offset:-0}
    command: [ "runRasp.sh","NETHERLANDS" ]

  netherlands4:
    image: blipmaps.nl/combined:latest
    build: .
    volumes:
      - /tmp/OUT:/root/rasp/NETHERLANDS/OUT
      - /tmp/LOG:/root/rasp/NETHERLANDS/LOG
    environment:
      - START_DAY=4
      - OFFSET_HOUR=${offset:-0}
    command: [ "runRasp.sh","NETHERLANDS" ]

  nl1km0:
    image: blipmaps.nl/combined:latest
    build: .
    volumes:
      - /tmp/OUT:/root/rasp/NL1KM/OUT
      - /tmp/LOG:/root/rasp/NL1KM/LOG
    environment:
      - START_DAY=0
      - OFFSET_HOUR=${offset:-0}
    command: [ "runRasp.sh","NL1KM" ]

  nl1km1:
    image: blipmaps.nl/combined:latest
    build: .
    volumes:
      - /tmp/OUT:/root/rasp/NL1KM/OUT
      - /tmp/LOG:/root/rasp/NL1KM/LOG
    environment:
      - START_DAY=1
      - OFFSET_HOUR=${offset:-0}
    command: [ "runRasp.sh","NL1KM" ]


  nl1km2:
    image: blipmaps.nl/combined:latest
    build: .
    volumes:
      - /tmp/OUT:/root/rasp/NL1KM/OUT
      - /tmp/LOG:/root/rasp/NL1KM/LOG
    environment:
      - START_DAY=2
      - OFFSET_HOUR=${offset:-0}
    command: [ "runRasp.sh","NL1KM" ]


