version: '3.7'

services:
  netherlands0:
    image: blipmaps.nl/combined:latest
    build: .
    volumes:
      - /tmp/OUT:/root/rasp/NETHERLANDS/OUT
      - /tmp/LOG:/root/rasp/NETHERLANDS/LOG
    environment:
      - START_DAY=0
      - OFFSET_HOUR=${offset:-0}
      - targetUrl=${targetUrl:-}
      - uploadXblFiles=${uploadXblFiles:-}
    command: [ "NETHERLANDS" ]
    secrets:
      - host_ssh_key
      - host_ssh_pub_key
      - host_ssh_known_hosts

  netherlands1:
    image: blipmaps.nl/combined:latest
    build: .
    volumes:
      - /tmp/OUT:/root/rasp/NETHERLANDS/OUT
      - /tmp/LOG:/root/rasp/NETHERLANDS/LOG
    environment:
      - START_DAY=1
      - targetUrl=${targetUrl:-}
      - OFFSET_HOUR=${offset:-0}
      - uploadXblFiles=${uploadXblFiles:-}
    command: [ "NETHERLANDS" ]
    secrets:
      - host_ssh_key
      - host_ssh_pub_key
      - host_ssh_known_hosts

  netherlands2:
    image: blipmaps.nl/combined:latest
    build: .
    volumes:
      - /tmp/OUT:/root/rasp/NETHERLANDS/OUT
      - /tmp/LOG:/root/rasp/NETHERLANDS/LOG
    environment:
      - START_DAY=2
      - targetUrl=${targetUrl:-}
      - OFFSET_HOUR=${offset:-0}
      - uploadXblFiles=${uploadXblFiles:-}
    command: [ "NETHERLANDS" ]
    secrets:
      - host_ssh_key
      - host_ssh_pub_key
      - host_ssh_known_hosts

  netherlands3:
    image: blipmaps.nl/combined:latest
    build: .
    volumes:
      - /tmp/OUT:/root/rasp/NETHERLANDS/OUT
      - /tmp/LOG:/root/rasp/NETHERLANDS/LOG
    environment:
      - START_DAY=3
      - targetUrl=${targetUrl:-}
      - OFFSET_HOUR=${offset:-0}
      - uploadXblFiles=${uploadXblFiles:-}
    command: [ "NETHERLANDS" ]
    secrets:
      - host_ssh_key
      - host_ssh_pub_key
      - host_ssh_known_hosts

  netherlands4:
    image: blipmaps.nl/combined:latest
    build: .
    volumes:
      - /tmp/OUT:/root/rasp/NETHERLANDS/OUT
      - /tmp/LOG:/root/rasp/NETHERLANDS/LOG
    environment:
      - START_DAY=4
      - targetUrl=${targetUrl:-}
      - OFFSET_HOUR=${offset:-0}
      - uploadXblFiles=${uploadXblFiles:-}
    command: [ "NETHERLANDS" ]
    secrets:
      - host_ssh_key
      - host_ssh_pub_key
      - host_ssh_known_hosts

  nl1km0:
    image: blipmaps.nl/combined:latest
    build: .
    volumes:
      - /tmp/OUT:/root/rasp/NL1KM/OUT
      - /tmp/LOG:/root/rasp/NL1KM/LOG
    environment:
      - START_DAY=0
      - targetUrl=${targetUrl:-}
      - OFFSET_HOUR=${offset:-0}
      - uploadXblFiles=${uploadXblFiles:-}
    command: [ "NL1KM" ]
    secrets:
      - host_ssh_key
      - host_ssh_pub_key
      - host_ssh_known_hosts

  nl1km1:
    image: blipmaps.nl/combined:latest
    build: .
    volumes:
      - /tmp/OUT:/root/rasp/NL1KM/OUT
      - /tmp/LOG:/root/rasp/NL1KM/LOG
    environment:
      - START_DAY=1
      - targetUrl=${targetUrl:-}
      - OFFSET_HOUR=${offset:-0}
      - uploadXblFiles=${uploadXblFiles:-}
    command: [ "NL1KM" ]
    secrets:
      - host_ssh_key
      - host_ssh_pub_key
      - host_ssh_known_hosts

  nl1km2:
    image: blipmaps.nl/combined:latest
    build: .
    volumes:
      - /tmp/OUT:/root/rasp/NL1KM/OUT
      - /tmp/LOG:/root/rasp/NL1KM/LOG
    environment:
      - START_DAY=2
      - targetUrl=${targetUrl:-}
      - OFFSET_HOUR=${offset:-0}
      - uploadXblFiles=${uploadXblFiles:-}
    command: [ "NL1KM" ]
    secrets:
      - host_ssh_key
      - host_ssh_pub_key
      - host_ssh_known_hosts

secrets:
  host_ssh_key:
    file: ~/.ssh/id_ed25519
  host_ssh_pub_key:
    file: ~/.ssh/id_ed25519.pub
  host_ssh_known_hosts:
    file: ~/.ssh/known_hosts
